"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var leitor = require("readline-sync");
var num1 = leitor.questionInt("Input a number");
var num2 = leitor.questionInt("Input another number");
var sum = num1 + num2;
var sub = num1 - num2;
var div = num1 / num2;
var mul = num1 * num2;
console.log("\n -------------------------------------- \n ");
console.log("The sum between ".concat(num1, " and ").concat(num2, " is ").concat(sum, " \n"));
console.log("The subtraction between ".concat(num1, " and ").concat(num2, " is ").concat(sub, " \n"));
console.log("The multiplication between ".concat(num1, " and ").concat(num2, " is ").concat(mul, " \n"));
console.log("The sum division ".concat(num1, " and ").concat(num2, " is ").concat(div, " \n"));
console.log("\n -------------------------------------- \n ");
var average = (sum + sub + div + mul) / 4;
console.log("The average is: ".concat(average, " "));
setTimeout(function () { }, 2000);
console.log("\n -------------------------------------- \n ");
